### ISSUE TITLE
Build errors on macOS 10.13.3

### ISSUE THREAD

**Issue by lanza** [m4b/rdr#9]
Sorry, I know absolutely nothing about ocaml to even begin diagnosing the issue, so I'll just copy paste the errors to a gist.

https://gist.github.com/lanza/bf176c06bbad4f7f5c12ddd45b148d69

**Comment by m4b** [comment]
Bytes need to be switched to String or vice versa. 

I don’t maintain this project anymore but I suppose I’ll merge a PR that fixes this. (I will not work on it though)

**Comment by ivg** [comment]
@lanza, my suggestion would be to use less fresh OCaml compiler. You're using 4.06 that is the latest and where they finally enforced the separation between bytes and strings. E.g., if you're using opam, then you can do 

```
opam switch 4.05.0
eval `opam config env`
```
and then install `rdr`. 

@m4b the hotfix could be adding `-unsafe-string` option to the compiler.

**Comment by m4b** [comment]
@lanza If you want a cli tool similar to rdr but better/maintained try https://github.com/m4b/bingrep

If you want to mess around with binary stuff in ocaml then I suggest you to the bap project: https://Github.com/binaryanalysisplatform/bap

**Comment by ivg** [comment]
the latter link should be https://github.com/BinaryAnalysisPlatform/bap or just http://bap.ece.cmu.edu :)
